server:
  port: ${SERVER_PORT:8762}
spring:
  application:
    name: kafka
  kafka:
    # kafka服务地址
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 10
      ack-mode: MANUAL_IMMEDIATE
      poll-timeout: 1500
    # 消费者配置
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: myGroup # 消费者群组ID，发布-订阅模式，即如果一个生产者，多个消费者都要消费，那么需要定义自己的群组，同一群组内的消费者只有一个能消费到消息。
      enable-auto-commit: true # 如果为true，消费者的偏移量将在后台定期提交。# 自动提交周期 auto-commit-interval: 100
      auto-offset-reset: earliest
      auto-commit-interval: 1000
      max-poll-records: 10
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # 生产者配置
    producer:
      # 指定消息key和消息体的编解码方式。
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 5 # 发送失败重试次数。
      batch-size: 16384 # 每次批量发送消息的数量 批处理条数：当多个记录被发送到同一个分区时，生产者会尝试将记录合并到更少的请求中。这有助于客户端和服务器的性能。
      buffer-memory: 33554432 # 批处理缓冲区大小 单位兆M。
      acks: 1